### PR TITLE
Getting started docs

### PR DESCRIPTION
**Pull request by mattlangeman**
This is a first pass at some new Getting Started docs. I went down a slight rabbit hole trying to add line highlighting to code previews, but ran into some prismjs CSS issues. I figure this is at least some progress and can continue to be improved.

### CODE REVIEW

**Comment by techniq** [comment]
Thanks @mattlangeman .  FWIW, I'd [like](https://github.com/techniq/svelte-ux/issues/62) to move away from PrismJS to possibly Shiki.  Been capturing some thoughts in that issue, but been low on the priorities.

Looking at the content now.

**Comment by mattlangeman** [comment]
@techniq Checking out Shiki now... I went with PrismJS on one of my side projects. I had a unique use case ([auto-scrolling the code preview](https://www.d3unchained.com/examples/scrolly-bar-chart-v1)) and was able to get it to work, but it wasn't super straightforward.

**Comment by techniq** [comment]
If we keep the content in `+page.md` and let mdsvex do it's think, we can get syntax highlighting and such (left preview of PR on vercel, right my local hacked up example)

image

image

**Comment by techniq** [comment]
The authoring experience with mdsvex has been painful, and one reason I've moved 99% of the content away from it, but it does help for pure doc pages (I have a handful in the Svelte UX docs still)

**Comment by mattlangeman** [comment]
> If we keep the content in `+page.md` and let mdsvex do it's thing, we can get syntax highlighting and such

Sounds and looks good. I have not used mdsvex, but happy to use it to get the syntax highlighting.

**Comment by percybolmer** [comment]
MDSvex uses PrismJS in the background but makes it a little easier by wrapping it, just a FYI.

**Comment by mattlangeman** [comment]
@techniq FYI: When separating Getting Started from the Home page I chose the lighting bolt home icon but I'm not attached to that :)

**Comment by mattlangeman** [comment]
> How about a play icon

Yup! That makes way more sense

> also, could you remove the old getting-started.md file?

Done!

**Pull request merged**
