### PR TITLE
Moves The yScale Function Requirements to Components

### PR DESCRIPTION
**Pull request by itsonlyjames**
Moves the need to apply scaling attributes on individual data elements to the component.

I have also setup a quick example in the docs showcasing how to use this approach.

Treemap component needs investigating as it uses some yScale function calls. 

Much cleaner approach 👍

### CODE REVIEW

**Comment by techniq** [comment]
Could you rebase this change?  It might be worth waiting until `design-tokens` is merged into `main` and then rebase onto `main`.  I use `graphite` which does a lot of rebase / re-writing history to manage PRs and can it cause a lot of these kinds of issues, sadly.

**Comment by itsonlyjames** [comment]
@techniq, will be much easier to rebase into main later. Not sure how it went from a working PR into a broken one but oh well., the fork commit still exists and can be rebased when you're ready!

**Comment by techniq** [comment]
Thanks @itsonlyjames .  We can always cherry-pick or just recreate.  I'm hoping to merge by next weekend.  Really had a goal to release by EOM, but starting a new job has thrown me off a few weeks.  Need more hours in the day.

**Comment by itsonlyjames** [comment]
@techniq agreed, not stressed about this. Easy to fix. Rather keep the history clean than have 8 lines of code destroy this. 
Congrats on the new job, and yeah tell me about it mate not enough hours in the day!

**Comment by techniq** [comment]
I'm going to re-open just so I don't loose track of it, but we'll close once we have can stack a new PR off main.  Thanks again!

**Comment by techniq** [comment]
Actually I just I can't because there are no longer commits related to the PR.  Would you mind writing up a really simple issue to track this?  No rush, just didn't want to forget about it :)

**Comment by itsonlyjames** [comment]
@techniq done – simple issue opened for history :)

**Comment by techniq** [comment]
@itsonlyjames Perfect, much appreciated!

**Pull request closed without merging**
