### PR TITLE
new sparkbar examples and changes to allow bar only highlights

### PR DESCRIPTION
**Pull request by mattlangeman**
Here are some Sparkbar examples. I ran into the situation of the current "area" Highlights not working well for Sparkbars, so I added "bar" highlights. Open to feedback on how this was implemented.

### CODE REVIEW

**Comment by techniq** [comment]
@mattlangeman I'm not against adding a new `Highlight` option, although another approach we could use it access the tooltip using `let:tooltip` and style the individual `Bar` using `getProps` (not overly sold on this name and might change it later).

https://github.com/techniq/layerchart/assets/177476/6bdf1f31-ab9a-4c2f-b0df-c3fb98333e5b

I used this approach to highlight some multi-line (and area) examples.  See this [post](https://twitter.com/techniq35/status/1705771880022417835) and follow up replies for a few examples.

With that said, I'm not against adding the tweening bar/rect shape.    We could maybe support this using `<Highlight area={{ snapToDataY: true }} >` similar to `TooltipContext`.

Thoughts?

**Comment by techniq** [comment]
> I actually first started looking into just changing the color of the bar directly. I didn't like duplicating the padding, stroke and radius. But I didn't come up with the `getProps` approach and thought I would need to then bring the tooltip into the bar component, which also didn't seem great.
> 
> You're thinking `snapToDataY` would replace the need for the extra `bar` prop to Highlight? Would we then also need `snapToDataX` for horizontal bar charts? I wonder if there is another name for this that would make sense.

That's what I was thinking, just to keep from having 2 props (`area` and `bar`) that were similar, and yes, there would be the compliment `snapToDataY`.  I'm open for another name, or inverting the meaning and having the full band width/height me the option.  There might also be a more elegant solution.  I'm also not completely against adding `bar` if it makes the most sense, just feeling out different approaches.

> Is there an example of the snapToData functionality somewhere? I found this note in the changelog, but it looks like at one point svelte-ux and layerchart were maybe in the same repo and now the release and commits have changed?
> 
> * [Tooltip] Add "Snap to data" options to examples ([09a92a](https://github.com/techniq/svelte-ux/commit/09a92a7b985259db2e350b26b4fd606294e69fa8))

I think that might be an overlook when I generated the initial changelog from commits (before I started using changesets).  If you notice, the actual commit is in the layerchart [repo](https://github.com/techniq/svelte-ux/commit/09a92a7b985259db2e350b26b4fd606294e69fa8).

Examples of the prop are available on the [Tooltip](https://www.layerchart.com/docs/components/Tooltip) component page, with the Scatter example having it enabled by default.

 image page

**Comment by techniq** [comment]
Another thought I had was to use a [clipPath](https://www.layerchart.com/docs/components/ClipPath) to "mask" the `<Highlight area={...} />` so it makes the same shape of the bars themselves, but I tried a few quick examples and wasn't having any success.  It would provide a slightly different effect to the spring/tweened shape `<Highlight bar>` provides.

I'm fine with leaving this PR as is for now, unless you want to explore some more.  I wish it didn't result in some duplication/added complexity within `Highlight`, but maybe we circle back on it later.

We could also extract a `Bar` component that is used within `Bars` and `Highlight`.

I'm thinking we could also remove the `getProps` and just expose a `bar` slot with slot props passed.

I have to say `createDimensionGetter` is rather ugly, but it was the best solution I came up with at the time.

**Comment by mattlangeman** [comment]
> Examples of the prop are available on the [Tooltip](https://www.layerchart.com/docs/components/Tooltip) component page

Ah. I see now. I was looking for code within the examples directory instead of across all docs. So snapToData in these examples is to fix the position of the Tooltip instead of having it move a bit based on cursor. That makes sense to me. I'd lean towards keeping the terminology different bar highlighting. The other thing I was thinking this morning is that it would be nice to allow both current area highlights and bar highlights at the same time. This could still be accomplished with only the `area` prop. Something like `area={'band'=true, 'bar'=true}`. And defaults could be `band=true` if backwards compatibility is desired.

I'm not in a hurry to get this PR merged in and wouldn't mind exploring a bit more. I have a busy day today, but plan to revisit tomorrow.

**Comment by techniq** [comment]
@mattlangeman Sounds great, and I'm not in a rush either :).  I'd rather refine and iterate, with the best abstraction to support the most use cases, with simplest implementation to simplify maintenance / additional use cases (you know, the holy grail).

> > Examples of the prop are available on the [Tooltip](https://www.layerchart.com/docs/components/Tooltip) component page
> 
> Ah. I see now. I was looking for code within the examples directory instead of across all docs. So snapToData in these examples is to fix the position of the Tooltip instead of having it move a bit based on cursor. That makes sense to me. I'd lean towards keeping the terminology different bar highlighting.

With TooltipContext / Tooltip, there are basically 3 ways to position:
- By default, [TooltipContext](https://github.com/techniq/layerchart/blob/master/src/lib/components/TooltipContext.svelte#L213-L214) will use the mouse/pointer position, and [Tooltip](https://github.com/techniq/layerchart/blob/master/src/lib/components/Tooltip.svelte#L14-L15) will apply an offset by default (mostly to not cover up the point you are interested in)
- In [TooltipContext](https://github.com/techniq/layerchart/blob/master/src/lib/components/TooltipContext.svelte#L73-L74), you can opt into snapping the position to the closest data point's X and/or Y
- In [Tooltip](https://github.com/techniq/layerchart/blob/master/src/lib/components/Tooltip.svelte#L10-L12), you can specify explicit `top` / `left` positions, overwriting/ignoring what is set in the TooltipContext. This was a recent addition we made for the Sparkline example, but I'd like to add more examples to show what kind of use cases this supports
  - A fixed tooltip in the top left (or any corner) by specifying values for both props (ex. `<Tooltip top={8} left={8} />`)
  - Only specifying a fixed `top` such as this visx [example](https://airbnb.io/visx/areas) or these Observable plot [examples](https://observablehq.com/plot/interactions/crosshair) which would use 2 instances of `<Tooltip>`, one with a fixed `top` and one with a fixed `left`.

> The other thing I was thinking this morning is that it would be nice to allow both current area highlights and bar highlights at the same time. This could still be accomplished with only the `area` prop. Something like `area={'band'=true, 'bar'=true}`. And defaults could be `band=true` if backwards compatibility is desired.
> 
> I'm not in a hurry to get this PR merged in and wouldn't mind exploring a bit more. I have a busy day today, but plan to revisit tomorrow.

One thing to note, is you can have multiple instances of both `<Highlight>` and `<Tooltip>`.  One example for `Highlight` is the [PunchCard](https://www.layerchart.com/docs/examples/PunchCard) example.  So we could also do `<Highlight area={{ mode: 'band' }}>` and also `<Highlight area={{ mode: 'bar' }}>`, although I also try to support using a single component when possible (why you see `<Highlight points lines />` used a lot to turn on both `points` and `lines`).

Also, the order you order the components matters (last one is on top, as it's `svg)`.  So...

```svelte
<Points>
<Highlight area />
```

...would put the `Highlight` on top of the the `Points` (and why it's 5% opaque by default).  While...

```svelte
<Highlight area />
<Points>
```

would put the `Highlight` behind the `Points`.  In some ways this is more aesthetically pleasing (but just depends on the general chart).

Sorry, this was as longer reply than I intended :).  One focus I hope to accomplishing before tagging the 1.0 release is to punch up the documentation a lot, trying to document and describe a lot of this "hidden" functionality/capability.  I'm also hoping as more users are using the library, it will naturally improve the docs.

Lastly, if you'd ever want to jump on a video chat to discuss anything, I'd be open for it.

**Comment by mattlangeman** [comment]
I was playing around with the bar highlighting again today. I tried sending in the tooltip to the Bar component so that it could be used to create the highlight within Bar. That allowed for creating the tweened bar, but without duplication of radius, stroke, etc. However, I realized that you may actually want to change the stroke for the highlight bar, and that led me back to thinking it may be best to create the rect within Highlight with the different modes.

The other idea was pulling in the context of Bar into Highlight via setContext and getContent and using that as defaults when creating the rect in Highlight.

It would be great to have a video call sometime. My schedule can be sporadic, but has also has some flexibility. Usually my ideal times are between 10am-4pm Eastern or in the evening after 8:30pm.

One topic I'm curious about is dealing with missing data and multiple datasets/different sources of data. A recent project had a unique challenges around those areas.

**Comment by techniq** [comment]
Evenings typically work best for me, as I too have a sporadic schedule (between work and 3 young kids/activities).  I've setup a discord server if you want to chat ([invite link](https://discord.gg/PePk6dwj)), and we can figure out the details when/how to do a video chat (google meet, zoom, teams, etc).  I'm actually off tomorrow and could chat during the day if you'd prefer.  Just let me know.

**Pull request merged**
